export const MATCH_LOAD_JSON = 'MATCH_LOAD_JSON';
export const MATCH_ADD = 'MATCH_ADD';
export const MATCH_SELECT_ITEM = 'MATCH_SELECT_ITEM';
export const MATCH_FILTER_OUTPUTS = 'MATCH_FILTER_OUTPUTS';
